/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mertins.viewgame;

import br.com.mertins.ufpel.fia.gameengine.elements.Peca;
import br.com.mertins.ufpel.fia.gameengine.elements.Tabuleiro;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author mertins
 */
public class JTabuleiro extends javax.swing.JPanel {

    /**
     * Creates new form JTabuleiro
     */
    public JTabuleiro() {
        initComponents();
    }
    private int sizeBloco = 60;
    private int size = 420;
    private Tabuleiro tabuleiro;

    public void setTabuleiro(Tabuleiro tabuleiro) {
        this.tabuleiro = tabuleiro;
        this.repaint();
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2d.setColor(Color.black);
        g2d.fillRect(0, 0, size, size);
        g2d.setColor(Color.green);
        g2d.drawRect(0, 0, size, size);
        for (int i = 0; i < 7; i++) {
            g2d.drawLine(0, i * sizeBloco, size, i * sizeBloco);
        }
        for (int i = 0; i < 7; i++) {
            g2d.drawLine(i * sizeBloco, 0, i * sizeBloco, size);
        }

        g2d.fillOval(184, 10, 50, 30); // Toca encima
        g2d.fillOval(184, 380, 50, 30); // Toca embaixo

        if (tabuleiro != null) {
            Peca[][] pecas = tabuleiro.getTabuleiro();
            int ajuste = 20;
            for (int y = 0; y < pecas.length; y++) {
                for (int x = 0; x < pecas.length; x++) {
                    if (pecas[y][x] != null) {
                        switch (pecas[y][x].getTipo()) {
                            case Toca:
                                break;
                            case Tiger:
                                g2d.drawString("T", x * sizeBloco + ajuste, y * sizeBloco + ajuste);
                            case Cat:
                                g2d.drawString("C", x * sizeBloco + ajuste, y * sizeBloco + ajuste);
                            case Dog:
                                g2d.drawString("D", x * sizeBloco + ajuste, y * sizeBloco + ajuste);
                            case Rat:
                                g2d.drawString("R", x * sizeBloco + ajuste, y * sizeBloco + ajuste);
                            case Elefant:
                                g2d.drawString("E", x * sizeBloco + ajuste, y * sizeBloco + ajuste);
                        }
                    }
                }
            }
        }
        g2d.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
